apiVersion: v1
kind: Service
metadata:
  name: finpay-api
  namespace: finpay
spec:
  type: NodePort
  selector:
    app: finpay-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
